### ISSUE TITLE
Collider warning on startup

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFutureSolar#20]
While going through my output_log.txt looking for something completely unrelated, I chanced across this: http://pastebin.com/0bvcMRHn

Apparently something in Unity doesn't agree with the way the colliders are set up for one of the blanket arrays. I don't know if this is an actual issue, or if it can safely be ignored... so I just thought I'd report it here.

**Comment by ChrisAdderley** [comment]
This has happened on a few parts, it has to do with mirrored geometry forming some of the panels. This has been a problem since the transition of KSP to unity 5, and Unity treats mirrored parts as identical, but with negative scale. The colliders therefore have negative scale.

There's nothing to do at this point except keep them under observation. I haven't noticed any behaviour problems with the parts that exhibit this (there are some in NFSpacecraft, particularly the cargo bay doors). Reanimating that whole panel with non-mirrrored components will be a pain in the ass for sure, which I would rather avoid.
