### ISSUE TITLE
SOL-A Expanding Curved Solar Array energy flow when retracted

### ISSUE THREAD

**Issue by pyalot** [ChrisAdderley/NearFutureSolar#6]
The SOL-A Expanding Curved Solar Array still produces energy flow after retraction.

![sol-a-flow-bug](https://cloud.githubusercontent.com/assets/592826/12006100/9a129e28-abc7-11e5-8e4c-5e0439f75231.jpeg)

**Comment by ChrisAdderley** [comment]
Weird. I'll check it out.

**Comment by ChrisAdderley** [comment]
GUI issue. When the panel retracts it stops updating to save resources, getting the UI stuck at the last update (no Ec was actually produced). Now will push a "Panel Retracted" note the UI when it retracts.

Fixed in https://github.com/ChrisAdderley/NearFutureSolar/commit/3f4b4f9daf82f546bf391de847158d677b14136a , will be in the next update.

**Comment by pyalot** [comment]
The other panels (stock or NFS) don't have the same issue, it's something specific to this panel. In the other panels energy flow display is set to 0 the instant they start retracting (not so in the SOL-A).

**Comment by ChrisAdderley** [comment]
Well this is the only panel that uses the CurvedSolarPanel module and also retracts/deploys, so it was the only one affected. As I mentioned, it's fixed in that commit
