### ISSUE TITLE
Deprecated parts replacements

### ISSUE THREAD

**Issue by kenshin23** [ChrisAdderley/NearFutureSolar#77]
Hi, I have a savefile that was using NFS version 1.0.5 and upon upgrading, it breaks most ships that are already in orbit due to some parts that are now deprecated. Is there an easy way to replace them with up-to-date parts on the latest version?

**Comment by ChrisAdderley** [comment]
There isn't - the reason parts were soft-deprecated until replacement was because physical and gameplay properties of the parts were changed in the redesign. Direct replacement will result in poor results for existing ships.
If you need the old files, download an older version of the mod (pre-1.1) and copy the `NearFutureSolar/Parts/Deprecated` folder into your `NearFutureSolar/Parts/` folder inside GameData. This will restore all the old parts.

**Comment by psychonaut25** [comment]
I ran into this same issue after updating to KSP 1.9.1.  I followed the advice here, adding the NearFutureSolar/Parts/Deprecated folder to NearFutureSolar/Parts/

Now TweakScale is giving me 16 fatal issues, all related to NFSolar parts.  Lisias took a look at my log file and told me that I'd failed to completely delete the TweakScale folder before updating to the latest version of TweakScale... but I did.  I did so multiple times.

TweakScale doesn't give me these issues without the Depreciated folder... I suppose I just wondered if anybody had any suggestions?
